AllCops:
  TargetRubyVersion: 2.2

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeSemicolon:
  Enabled: true


Lint/DuplicateMethods:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true


Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# Offense count: 13
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 80

Metrics/MethodLength:
  Enabled: false

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 8


Performance/RedundantBlockCall:
  Enabled: true


Naming/MethodName:
  Enabled: true

Naming/BinaryOperatorParameterName:
  Enabled: true


Style/ClassVars:
  Enabled: true

Style/Documentation:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/NumericLiterals:
  MinDigits: 5

Style/PreferredHashMethods:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/SingleLineMethods:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Style/UnneededPercentQ:
  Enabled: true

Style/DateTime:
  Enabled: false
