inherit_from: .rubocop_todo.yml

Lint/DuplicateMethods:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true


Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# Offense count: 13
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 80

Metrics/MethodLength:
  Enabled: false

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 8


Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: true

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
