require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.2
  NewCops: enable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Lint/MissingSuper:
  Exclude:
    - lib/timezone/lookup/test.rb 

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# Offense count: 13
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Layout/LineLength:
  Max: 80

Metrics/MethodLength:
  Enabled: false

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 8

Style/NumericLiterals:
  MinDigits: 5

Style/OpenStructUse:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/DateTime:
  Enabled: false
